### PR TITLE
Updated angular2-hotkeys; @angular-devkit/build-angular. scss @import…

### PR DESCRIPTION
**Pull request by DerekHill**
… _main

### CODE REVIEW

**Comment by mityalebedev** [comment]
I think it's may be bug somewhere, not in our code maybe in angular preprocessor. 
BTW i did not have same error on my end, only see notice in WebStorm, but all builds a passing well.

**Comment by DerekHill** [comment]
@mityalebedev I'm afraid that at some point when updating dependencies I introduced the error in `edfu/apps/erya/src/styles.scss`:

>  SassError: Can't find stylesheet to import.
>   ╷
> 2 │ @import "main";
>   │         ^^^^^^
>   ╵

For the moment I have changed this to `@import "_main"`

Trello card: https://trello.com/c/DAUuM5wO/42-sasserror-cant-find-stylesheet-to-import-changed-import-main-to-import-main

Sorry for this.

**Comment by DerekHill** [comment]
@mityalebedev just saw your comment.  Anyway.  Will merge this, and then we can go from here.

**Comment by mityalebedev** [comment]
Ok cool @DerekHill

**Pull request merged**
