### PR TITLE
Adjust main stylesheet import

### PR DESCRIPTION
**Pull request by DerekHill**
@mityalebedev I wonder if there is some difference between Webstorm and vscode (which I am using).

For me I get this error:

> SassError: Can't find stylesheet to import.
>   ╷
> 2 │ @import 'src/assets/stylesheets/main';
>   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ╵
>   /Users/derekhill/code/makaton/edfu/apps/erya/src/styles.scss 2:9  root stylesheet

And then changing the import per the attached fixes it.

Not sure if the best way forward is this PR, or if there is a different way.   Would leave this to you if that's ok. 

Screenshot 2020-03-11 at 11 05 33

### CODE REVIEW

**Comment by mityalebedev** [comment]
@DerekHill Thats strange.  We are using `stylePreprocessorOptions` 

https://github.com/DerekHill/edfu/blob/dc3a3202aefc1f6bb36f3363e7166686aecaa360/angular.json#L26-L29

Then we able just use `@import "main";` without long path.
I have an error in IDE, but no errors in builds.

image

**Comment by DerekHill** [comment]
@mityalebedev I found that if I rename `main.scss` to `variables.scss` then it does work.  

I got the idea from:
 - https://github.com/angular/angular-cli/issues/15126#issuecomment-513196845
 - https://github.com/angular/angular-cli/issues/15254#issuecomment-518979381

**Comment by mityalebedev** [comment]
It's not a "variables", but it's ok for now.
But what happens in the future if we would like to import other styles later?

I mainly use old 2018 WS and  it's a known problem for me https://youtrack.jetbrains.com/issue/WEB-32648 - so renaming does not fix it. 

Just checked on latest 2020WS all works fine even if import `_main.scss` as "main" without dash.

Also i did not had any errors during build not now not before. Do you run `ng serve` inside VS?
Maybe try to remove node_modules and install from scratch...

**Comment by DerekHill** [comment]
>  Do you run ng serve inside VS?

No. I run this in the terminal.

> Maybe try to remove node_modules and install from scratch...

Ok.  Will try.

**Comment by DerekHill** [comment]
@mityalebedev reinstalling node_modules did not work.

It is possible you are using an older version of @angular/cli?  I am on 9.0.5.

I did find some more references to this problem:
 - https://stackoverflow.com/questions/57164159/stylepreprocessoroptions-angular-8
 - https://stackoverflow.com/questions/59715916/how-to-use-sass-loader-in-angular

I did find this issue on sass-loader (https://github.com/webpack-contrib/sass-loader/issues/704).  This says:

> we're hoping to improve the JS API and the default Sass behavior to make this much more foolproof, probably in early 2020.

I tried updating that from v `8.0.0` to `8.0.2` but that did not help

> It's not a "variables", but it's ok for now.

If it's ok with you I would propose to merge this.

> But what happens in the future if we would like to import other styles later?

I'm not sure. Hopefully this is related to sass-loader and it would have been fixed.

Are you ok to merge?

**Comment by mityalebedev** [comment]
`9.0.5` No errors with`_main.scss` and `@import "main";`
image

You can merge it now, we can back to this later.

**Comment by DerekHill** [comment]
So strange.  It works for me if both the filename and import are `_main`

> You can merge it now, we can back to this later.

Great. Thanks.  Will do that when this passes.

**Pull request merged**
